# DS4PH 2022 HW 2
## created by bhu22

* *Problem 1 sorting hat* 

In [1]:
Q1 = input('Do you like snakes (Y/N)? ')

Do you like snakes (Y/N)? N


In [2]:
Q2 = input('Do you like lions (Y/N)? ')

Do you like lions (Y/N)? Y


In [3]:
Q3 = input('Do you like eagles (Y/N)? ')

Do you like eagles (Y/N)? N


In [4]:
if Q1=='Y': 
    print('Slytherine!')
elif Q2=='Y' and Q3=='N':
    print('Gryffindor!')
elif Q2=='N' and Q3=='Y':
    print('Ravenclaw!')
else:
    print('Hufflepuff')

Gryffindor!


* *Problem 2 Write an object*

In [5]:
import numpy as np

In [6]:
class mydata:
    def __init__(self,vector):
        self.vector = vector
        
    def mean(self):
        return np.mean(self.vector)
    
    def std(self):
        return np.std(self.vector)
        

In [7]:
md = mydata([1, 2, 3, 4])

In [8]:
md.mean()

2.5

In [9]:
md.std()

1.118033988749895

* *Problem 3 Create a lag function*

In [10]:
def lag(vector, n):
    vector_arr = np.array(vector)
    removed_arr= vector_arr[:-n]
    empty_value = np.empty(n)
    empty_value[:]= np.nan
#     new_vector = list(empty_value) + list(removed_arr)
    new_vector = np.concatenate((empty_value,removed_arr))  
    return new_vector
    

In [11]:
a = [1,6,8,4]

In [12]:
lag(a,1)

array([nan,  1.,  6.,  8.])

In [13]:
lag(a,2)

array([nan, nan,  1.,  6.])

* *Problem 4 Create a lag function generator*

In [14]:
def lagGenerator(n):
    return lambda x: lag(x,n)

In [15]:
a = [1,6,8,4]

In [16]:
lagGen1 = lagGenerator(1)

In [17]:
lagGen1(a)

array([nan,  1.,  6.,  8.])

In [18]:
lagGen2 = lagGenerator(2)

In [19]:
lagGen2(a)

array([nan, nan,  1.,  6.])